import { useEffect, useRef, useState } from 'react'
import { ApiError } from '../../lib/apiClient.js'
import { accountService } from '../../services/accountService.js'
import { orderService } from '../../services/orderService.js'
import { lookupCep } from '../../services/cepService.js'
import { shippingService } from '../../services/shippingService.js'
import { useCart } from '../cart/CartContext.jsx'
import { formatCurrency, productCents } from '../cart/cartValidation.js'

const orderStatus = { PendingPayment: ['Aguardando pagamento', 'warning'], Paid: ['Pagamento confirmado', 'success'], InProduction: ['Em produção', 'info'], ReadyToShip: ['Pronto para envio', 'info'], Shipped: ['Enviado', 'info'], Delivered: ['Entregue', 'success'], Cancelled: ['Cancelado', 'danger'] }
const paymentPending = status => status === 'PendingPayment'
const navigate = path => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
const message = error => error?.status === 401 ? 'Entre na sua conta para continuar.' : error?.message || 'Não foi possível concluir a solicitação.'

function StoreHeader() { const { totalQuantity } = useCart(); return <header className="commerce-header"><a href="/" className="commerce-brand">TRISO<small>STUDIO</small></a><nav><a href="/minha-conta">Minha conta</a><a href="/carrinho">Carrinho <b>{totalQuantity}</b></a></nav></header> }
function Layout({ children }) { return <><StoreHeader/><main className="commerce-page">{children}</main></> }
function Line({ line, editable }) { const { setQuantity, remove } = useCart(); return <article className="commerce-line"><div className="commerce-thumb">{line.product.imageUrl ? <img src={line.product.imageUrl} alt=""/> : null}</div><div><b>{line.product.name}</b><small>{formatCurrency(productCents(line.product))} cada</small>{editable && <div className="quantity"><button onClick={() => setQuantity(line.productId, line.quantity - 1)} aria-label="Diminuir quantidade">−</button><span>{line.quantity}</span><button onClick={() => setQuantity(line.productId, line.quantity + 1)} aria-label="Aumentar quantidade">+</button></div>}</div><strong>{formatCurrency(productCents(line.product) * line.quantity)}</strong>{editable && <button className="commerce-link danger" onClick={() => remove(line.productId)}>Remover</button>}</article> }

export function CartPage() { const { lines, subtotalCents, clear } = useCart(); return <Layout><section className="commerce-card"><span className="commerce-kicker">COMPRA / CARRINHO</span><h1>Seu carrinho</h1>{lines.length ? <><div className="commerce-lines">{lines.map(line => <Line key={line.productId} line={line} editable/>)}</div><div className="commerce-total"><span>Subtotal <small>Frete será informado pelo atendimento.</small></span><strong>{formatCurrency(subtotalCents)}</strong></div><div className="commerce-actions"><button className="commerce-secondary" onClick={() => { if (window.confirm('Remover todos os itens do carrinho?')) clear() }}>Limpar carrinho</button><a className="commerce-primary" href="/checkout">Continuar para checkout</a></div></> : <div className="commerce-empty"><h2>Seu carrinho está vazio.</h2><a className="commerce-primary" href="/">Ver produtos</a></div>}</section></Layout> }

function AuthForm({ register = false }) { const [form, setForm] = useState({ name: '', email: '', password: '', confirmation: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const target = sessionStorage.getItem('triso_return_to') || '/minha-conta'; const submit = async event => { event.preventDefault(); if (register && form.password !== form.confirmation) return setError('As senhas não coincidem.'); setBusy(true); setError(''); try { const user = register ? await accountService.register(form) : await accountService.login(form); if (!user) throw new Error('Esta conta não é uma conta de cliente.'); sessionStorage.removeItem('triso_return_to'); navigate(target) } catch (err) { setError(message(err)); setBusy(false) } }; return <Layout><section className="commerce-auth"><span className="commerce-kicker">CONTA / {register ? 'CADASTRO' : 'ENTRAR'}</span><h1>{register ? 'Crie sua conta' : 'Entre na sua conta'}</h1><form onSubmit={submit}>{register && <label>Nome<input required minLength="2" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })}/></label>}<label>E-mail<input required type="email" autoComplete="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })}/></label><label>Senha<input required minLength="8" type="password" autoComplete={register ? 'new-password' : 'current-password'} value={form.password} onChange={event => setForm({ ...form, password: event.target.value })}/></label>{register && <label>Confirme a senha<input required minLength="8" type="password" autoComplete="new-password" value={form.confirmation} onChange={event => setForm({ ...form, confirmation: event.target.value })}/></label>}{error && <p className="commerce-error" role="alert">{error}</p>}<button className="commerce-primary" disabled={busy}>{busy ? 'Processando...' : register ? 'Criar conta' : 'Entrar'}</button></form><p>{register ? <>Já possui conta? <a href="/entrar">Entrar</a></> : <>Ainda não tem conta? <a href="/cadastro">Criar conta</a></>}</p></section></Layout> }
export const LoginPage = () => <AuthForm/>
export const RegisterPage = () => <AuthForm register/>

const emptyAddress = { recipientName: '', street: '', number: '', complement: '', neighborhood: '', city: '', state: '', postalCode: '' }
export function CheckoutPage() {
  const { lines, subtotalCents } = useCart()
  const [user, setUser] = useState(undefined)
  const [address, setAddress] = useState(emptyAddress)
  const [error, setError] = useState('')
  const [cepLoading, setCepLoading] = useState(false)
  const [quotes, setQuotes] = useState([])
  const [shippingQuoteId, setShippingQuoteId] = useState('')
  const [quoting, setQuoting] = useState(false)
  const [busy, setBusy] = useState(false)
  const orderRef = useRef(null)
  const quotedKeyRef = useRef('')
  const cep = address.postalCode.replace(/\D/g, '')
  const itemsKey = lines.map(line => `${line.productId}:${line.quantity}`).join('|')
  const addressReady = ['recipientName', 'postalCode', 'street', 'number', 'neighborhood', 'city', 'state'].every(key => String(address[key] || '').trim()) && /^\d{8}$/.test(cep) && /^[a-z]{2}$/i.test(address.state.trim())

  useEffect(() => { accountService.session().then(currentUser => { setUser(currentUser); if (currentUser?.name) setAddress(current => ({ ...current, recipientName: current.recipientName || currentUser.name })) }).catch(() => setUser(null)) }, [])
  useEffect(() => { if (user === null) { sessionStorage.setItem('triso_return_to', '/checkout'); navigate('/entrar') } }, [user])
  useEffect(() => {
    if (cep.length !== 8) return
    const controller = new AbortController()
    const timer = window.setTimeout(async () => {
      setCepLoading(true); setError('')
      try {
        const found = await lookupCep(cep, controller.signal)
        setAddress(current => current.postalCode.replace(/\D/g, '') === cep ? { ...current, ...found, complement: current.complement, number: current.number, recipientName: current.recipientName } : current)
      } catch (err) { if (err.name !== 'AbortError') setError(err.message) } finally { if (!controller.signal.aborted) setCepLoading(false) }
    }, 250)
    return () => { window.clearTimeout(timer); controller.abort() }
  }, [cep])
  useEffect(() => {
    if (cep.length !== 8 || !itemsKey) { quotedKeyRef.current = ''; setQuotes([]); setShippingQuoteId(''); return }
    const requestKey = `${cep}|${itemsKey}`
    if (quotedKeyRef.current === requestKey) return
    const controller = new AbortController()
    const timer = window.setTimeout(async () => {
      setQuoting(true); setError(''); setQuotes([]); setShippingQuoteId('')
      try {
        const result = await shippingService.quote(cep, lines, controller.signal)
        quotedKeyRef.current = requestKey
        setQuotes(result.quotes || [])
      } catch (err) { if (err.name !== 'AbortError') setError(message(err)) } finally { if (!controller.signal.aborted) setQuoting(false) }
    }, 250)
    return () => { window.clearTimeout(timer); controller.abort() }
  }, [cep, itemsKey, lines])

  if (!lines.length) return <CartPage/>
  const selectedQuote = quotes.find(quote => quote.id === shippingQuoteId)
  const submit = async event => { event.preventDefault(); if (busy || !user) return; setBusy(true); setError(''); const normalized = { ...address, postalCode: cep, state: address.state.trim().toUpperCase() }; if (!addressReady) { setBusy(false); return setError('Complete os dados obrigatórios de entrega.') } if (!shippingQuoteId) { setBusy(false); return setError('Selecione uma opção de entrega para continuar.') } try { const order = orderRef.current || await orderService.create(lines.map(line => ({ productId: line.productId, quantity: line.quantity })), normalized, shippingQuoteId); orderRef.current = order; const id = order.id; sessionStorage.setItem('triso_current_order', JSON.stringify({ id, items: lines.map(line => ({ productId: line.productId, quantity: line.quantity })) })); const checkout = await orderService.checkout(id); const url = new URL(checkout.checkoutUrl); if (url.protocol !== 'https:' || !/(^|\.)infinitepay\.io$/i.test(url.hostname)) throw new Error('O endereço de pagamento retornado não é válido.'); window.location.assign(url.toString()) } catch (err) { setError(message(err)); setBusy(false) } }
  return <Layout><section className="checkout-grid"><form className="commerce-card checkout-form" onSubmit={submit}><span className="commerce-kicker">CHECKOUT / 1 IDENTIFICAÇÃO · 2 ENTREGA · 3 PAGAMENTO</span><h1>Entrega e pagamento</h1><p>Olá, {user?.name}. Informe o CEP para preencher o endereço e calcular o frete.</p><div className="commerce-fields">{[['postalCode','CEP'],['street','Rua'],['number','Número'],['complement','Complemento'],['neighborhood','Bairro'],['city','Cidade'],['state','Estado']].map(([key,label]) => <label key={key}>{label}<input required={key !== 'complement'} inputMode={key === 'postalCode' ? 'numeric' : undefined} maxLength={key === 'state' ? 2 : key === 'postalCode' ? 9 : undefined} value={address[key]} onChange={event => setAddress({ ...address, [key]: key === 'state' ? event.target.value.toUpperCase() : event.target.value })}/>{key === 'postalCode' && cepLoading && <small>Consultando CEP...</small>}</label>)}</div><section className="shipping-quotes" aria-live="polite"><div className="shipping-quotes-heading"><span>ENTREGA</span><h2>Escolha o frete</h2><small>Valores e prazos para o seu CEP</small></div>{quoting&&<div className="shipping-quote-loading">Calculando opções de entrega...</div>}{!quoting&&quotes.map(quote=><label key={quote.id} className={`shipping-option ${shippingQuoteId===quote.id?'selected':''}`}><input type="radio" name="shippingQuote" value={quote.id} checked={shippingQuoteId===quote.id} onChange={()=>setShippingQuoteId(quote.id)}/><i className="shipping-option-radio"/><span className="shipping-option-copy"><b>{quote.carrier} · {quote.service}</b><small>Chega em até {quote.deliveryDays} dias úteis</small></span><span className="shipping-option-price"><small>Frete</small><strong>{formatCurrency(quote.priceCents)}</strong></span></label>)}{!quoting&&cep.length===8&&!quotes.length&&<p className="shipping-quote-empty">Não há opções disponíveis para este CEP.</p>}</section>{error && <p className="commerce-error" role="alert">{error}</p>}<button className="commerce-primary" disabled={busy}>{busy ? 'Criando pedido...' : 'Ir para pagamento seguro'}</button></form><aside className="commerce-card checkout-summary"><span className="commerce-kicker">SEU PEDIDO</span><h2>Resumo da compra</h2><div className="checkout-summary-lines">{lines.map(line => <Line key={line.productId} line={line}/>)}</div><div className="summary-breakdown"><div><span>Produtos</span><strong>{formatCurrency(subtotalCents)}</strong></div><div><span>Entrega{selectedQuote&&<small>{selectedQuote.carrier} · {selectedQuote.service}</small>}</span><strong>{selectedQuote?formatCurrency(selectedQuote.priceCents):'A calcular'}</strong></div></div><div className="summary-total"><span>Total</span><strong>{formatCurrency(subtotalCents+(selectedQuote?.priceCents||0))}</strong></div><p className="summary-note">O valor final considera o frete selecionado.</p></aside></section></Layout>
}

function StatusBadge({ status }) { const [label, tone] = orderStatus[status] || [status, 'info']; return <span className={`status-badge ${tone}`}>{label}</span> }
export function ConfirmationPage({ orderId }) { const { clearPurchased } = useCart(); const [order, setOrder] = useState(null); const [state, setState] = useState('loading'); const load = async () => { try { const next = await orderService.get(orderId); setOrder(next); setState(next.status === 'Paid' ? 'paid' : 'pending'); if (next.status === 'Paid') { const current = JSON.parse(sessionStorage.getItem('triso_current_order') || 'null'); if (current?.id === orderId) { clearPurchased(current.items); sessionStorage.removeItem('triso_current_order') } } } catch (error) { setState(error.status === 404 ? 'missing' : 'error') } }; useEffect(() => { load(); let elapsed = 0; const timer = setInterval(() => { elapsed += 3000; if (elapsed >= 60000) { clearInterval(timer); if (state !== 'paid') setState('timeout') } else load() }, 3000); return () => clearInterval(timer) }, [orderId]); return <Layout><section className="commerce-card confirmation"><span className="commerce-kicker">PEDIDO / CONFIRMAÇÃO</span>{state === 'loading' && <><h1>Confirmando seu pagamento...</h1><p>A confirmação é feita diretamente pelo nosso sistema de pedidos.</p></>}{state === 'paid' && <><h1>Pagamento confirmado!</h1><StatusBadge status={order.status}/><p>Pedido {order.orderNumber} recebido. Vamos iniciar a produção em breve.</p><a className="commerce-primary" href={`/minha-conta/pedidos/${orderId}`}>Ver pedido</a></>}{['pending','timeout'].includes(state) && <><h1>Aguardando confirmação</h1><p>{state === 'timeout' ? 'Ainda estamos aguardando a confirmação do pagamento. Você pode atualizar novamente em alguns instantes.' : 'Seu pagamento ainda está sendo confirmado.'}</p>{order && <StatusBadge status={order.status}/>}<button className="commerce-primary" onClick={load}>Atualizar pagamento</button></>}{state === 'missing' && <><h1>Pedido não encontrado</h1><a href="/minha-conta/pedidos">Ver meus pedidos</a></>}{state === 'error' && <><h1>Não foi possível consultar o pedido</h1><button className="commerce-primary" onClick={load}>Tentar novamente</button></>}</section></Layout> }

export function AccountPage({ detailId }) { const [profile, setProfile] = useState(null); const [orders, setOrders] = useState(null); const [detail, setDetail] = useState(null); const [error, setError] = useState(''); useEffect(() => { const controller = new AbortController(); Promise.all([accountService.profile(controller.signal), orderService.list(controller.signal)]).then(([nextProfile, nextOrders]) => { setProfile(nextProfile); setOrders(nextOrders); if (detailId) return orderService.get(detailId, controller.signal).then(setDetail) }).catch(err => { if (err.name !== 'AbortError') setError(message(err)) }); return () => controller.abort() }, [detailId]); const logout = async () => { await accountService.logout(); navigate('/') }; if (error) return <Layout><section className="commerce-card"><p className="commerce-error">{error}</p><a href="/entrar">Entrar novamente</a></section></Layout>; return <Layout><section className="commerce-card account"><span className="commerce-kicker">MINHA CONTA</span><h1>{detail ? `Pedido ${detail.orderNumber}` : profile ? `Olá, ${profile.name}` : 'Carregando conta...'}</h1>{detail ? <><StatusBadge status={detail.status}/><div className="commerce-lines">{detail.items.map(item => <article className="commerce-line" key={item.productId}><div><b>{item.productName}</b><small>{item.quantity} × {formatCurrency(item.unitPriceCents)}</small></div><strong>{formatCurrency(item.totalCents)}</strong></article>)}</div><p><b>Entrega:</b> {detail.address.street}, {detail.address.number} — {detail.address.city}/{detail.address.state}</p><p><b>Total:</b> {formatCurrency(detail.totalCents)}</p>{paymentPending(detail.status) && <button className="commerce-primary" onClick={async event => { event.currentTarget.disabled = true; try { const checkout = await orderService.checkout(detail.id); const url = new URL(checkout.checkoutUrl); if (url.protocol !== 'https:' || !/(^|\.)infinitepay\.io$/i.test(url.hostname)) throw new Error('URL de pagamento inválida.'); window.location.assign(url) } catch (err) { setError(message(err)); event.currentTarget.disabled = false } }}>Tentar pagamento novamente</button>}</> : <><p>{profile?.email}</p><h2>Meus pedidos</h2>{orders?.length ? <div className="commerce-orders">{orders.map(order => <a href={`/minha-conta/pedidos/${order.id}`} key={order.id}><span><b>{order.orderNumber}</b><small>{new Date(order.createdAt).toLocaleDateString('pt-BR')}</small></span><StatusBadge status={order.status}/><strong>{formatCurrency(order.totalCents)}</strong></a>)}</div> : orders && <p>Nenhum pedido realizado ainda.</p>}<button className="commerce-secondary" onClick={logout}>Sair</button></>}</section></Layout> }

export function PaymentReturnPage() { const saved = JSON.parse(sessionStorage.getItem('triso_current_order') || 'null'); return saved?.id ? <ConfirmationPage orderId={saved.id}/> : <Layout><section className="commerce-card"><h1>Não foi possível identificar o pedido.</h1><a href="/minha-conta/pedidos">Ver meus pedidos</a></section></Layout> }
