import { useEffect, useState } from "react";
import { TrisoLogo } from "../../components/TrisoLogo.jsx";
const fitaIsabella4 = "/Triso/Apresentacao/Lembranca_exemplo.png";

const steps = [
  { number: "01", title: "Escolha sua foto", text: "A pessoa seleciona uma imagem no celular ou computador.", icon: "image" },
  { number: "02", title: "Ajuste o enquadramento", text: "Ela posiciona a foto e controla o zoom para encaixar no selo.", icon: "crop" },
  { number: "03", title: "Gere e compartilhe", text: "A arte fica pronta para baixar e publicar onde quiser.", icon: "share" },
];
const manualItems = [
  ["Materiais necessários", "Envie seu logotipo em boa qualidade, paleta de cores, nome da campanha, textos, referências visuais, redes sociais e o objetivo da ação."],
  ["Criação e aprovação", "A Triso desenvolve a identidade do selo, configura sua página e envia uma prévia para aprovação antes da publicação."],
  ["Publicação do site", "Depois da aprovação, sua campanha recebe um link exclusivo para ser divulgado em todos os seus canais."],
  ["Divulgação da campanha", "Compartilhe o link na bio, Stories, WhatsApp, QR Codes e publicações. Use a mensagem pronta abaixo para convidar sua comunidade."],
  ["Como orientar participantes", "A pessoa acessa o link, escolhe uma foto, ajusta o enquadramento, gera o selo e baixa ou compartilha a imagem final."],
  ["Perguntas frequentes", "O site funciona no celular e no computador. Não é necessário instalar aplicativo nem criar uma conta para gerar o selo."],
];
const benefits = [["Identidade visual personalizada", "Selo desenvolvido com as cores e elementos da sua marca."], ["Página exclusiva", "Um endereço próprio para divulgar sua campanha."], ["Editor responsivo", "Experiência intuitiva em celulares e computadores."], ["Imagem pronta para compartilhar", "Resultado final preparado para baixar e publicar."]];
const shareMessage = "Faça parte da nossa comunidade! Acesse o link, escolha sua foto e crie seu selo personalizado para compartilhar.";

const whatsappHref = "https://wa.me/5511966435518?text=Ol%C3%A1%2C%20quero%20solicitar%20um%20site%20personalizado%20da%20Triso.";

function Icon({ name }) {
  const paths = { image: <><rect x="3" y="4" width="18" height="16" rx="2" /><circle cx="8" cy="9" r="1.5" /><path d="m4 17 5-5 3.5 3.5 2.5-2.5 4 4" /></>, crop: <><path d="M7 3v14a4 4 0 0 0 4 4h10" /><path d="M17 3H7" /><path d="M3 7h14a4 4 0 0 1 4 4v10" /></>, share: <><circle cx="18" cy="5" r="2.5" /><circle cx="6" cy="12" r="2.5" /><circle cx="18" cy="19" r="2.5" /><path d="m8.2 10.8 7.5-4.4M8.2 13.2l7.5 4.4" /></>, bolt: <path d="m13 2-9 12h7l-1 8 9-12h-7z" />, phone: <rect x="7" y="2.5" width="10" height="19" rx="2" />, download: <><path d="M12 3v12" /><path d="m7.5 10.5 4.5 4.5 4.5-4.5" /><path d="M4 21h16" /></>, arrow: <><path d="M5 12h13" /><path d="m13 6 6 6-6 6" /></>, external: <><path d="M14 4h6v6" /><path d="m20 4-9 9" /><path d="M19 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h5" /></> };
  return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>;
}

export function PresentationHomePage() {
  return <main className="sales-home"><header className="sales-home-header"><TrisoLogo light /><span>APRESENTAÇÕES TRISO STUDIO</span></header><section className="sales-home-hero"><span className="sales-kicker">TRISO STUDIO</span><h1>Experiências que transformam momentos em <em>memórias.</em></h1><p>Escolha uma apresentação para conhecer as soluções digitais da Triso Studio.</p><div className="sales-home-options"><a href="/apresentacao-selo" className="sales-home-option"><span>PARA EMPRESAS</span><h2>Selos para comunidades</h2><p>Campanhas personalizadas, páginas exclusivas e experiências para engajar sua comunidade.</p><b>Ver apresentação <Icon name="arrow" /></b></a><a href="/apresentacao-festas" className="sales-home-option party"><span>PARA FESTAS</span><h2>Fotos para festas e eventos</h2><p>Molduras personalizadas para convidados criarem e compartilharem suas próprias lembranças.</p><b>Ver apresentação <Icon name="arrow" /></b></a></div></section><footer className="sales-home-footer"><TrisoLogo light /><a href="https://wa.me/551196435518" target="_blank" rel="noreferrer">Falar com a Triso Studio</a></footer></main>;
}

export function SalesTemplatePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [openManual, setOpenManual] = useState(0);
  const [copied, setCopied] = useState(false);
  const copyMessage = async () => { try { await navigator.clipboard.writeText(shareMessage); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } };
  const closeMenu = () => setMenuOpen(false);
  useEffect(() => {
    const contactUrl = "https://wa.me/5511966435518?text=Ol%C3%A1%2C%20quero%20criar%20uma%20experi%C3%AAncia%20com%20a%20Triso.";
    document.querySelectorAll('.sales-page:not(.sales-party-page) a[href^="mailto:"]').forEach((link) => {
      link.href = contactUrl;
      link.target = "_blank";
      link.rel = "noreferrer";
    });
  }, []);
  return <main className="sales-page"><a className="sales-back-link" href="/apresentacao">Voltar</a>
    <header className="sales-header"><div className="sales-header-inner"><TrisoLogo light /><nav className="sales-nav" aria-label="Navegação principal"><a href="#como-funciona">Como funciona</a><a href="#demonstracao">Demonstração</a><a href="#exemplos">Exemplos</a><a href="#manual">Manual</a><a href="#beneficios">Benefícios</a></nav><a className="sales-header-cta" href="mailto:oi@triso.com.br?subject=Solicitar%20meu%20site">Solicitar meu site <Icon name="arrow" /></a><button className="sales-menu-button" type="button" aria-label="Abrir menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(open => !open)}><i /><i /><i /></button></div><nav className={`sales-mobile-nav ${menuOpen ? "open" : ""}`} aria-label="Navegação mobile"><a href="#como-funciona" onClick={closeMenu}>Como funciona</a><a href="#demonstracao" onClick={closeMenu}>Demonstração</a><a href="#exemplos" onClick={closeMenu}>Exemplos</a><a href="#manual" onClick={closeMenu}>Manual</a><a href="#beneficios" onClick={closeMenu}>Benefícios</a><a href="mailto:oi@triso.com.br?subject=Solicitar%20meu%20site">Solicitar meu site</a></nav></header>
    <section className="sales-hero" aria-labelledby="sales-title"><div className="sales-hero-copy"><span className="sales-kicker">SITES PERSONALIZADOS PARA SUA COMUNIDADE</span><h1 id="sales-title">Seu site de selos, pronto para <em>engajar sua comunidade.</em></h1><p>Transforme sua marca em uma experiência interativa. Seu público envia uma foto, aplica o selo personalizado da sua empresa e compartilha o resultado.</p><div className="sales-actions"><a className="sales-button sales-primary" href="mailto:oi@triso.com.br?subject=Solicitar%20meu%20site">Solicitar meu site <Icon name="arrow" /></a><a className="sales-button sales-secondary" href="#demonstracao">Ver demonstração <Icon name="arrow" /></a></div><div className="sales-hero-benefits"><span><i><Icon name="bolt" /></i><small>Página exclusiva<br />com sua identidade</small></span><span><i><Icon name="phone" /></i><small>Experiência otimizada<br />para celular</small></span><span><i><Icon name="download" /></i><small>Imagem pronta<br />para compartilhar</small></span></div></div><div className="sales-hero-result" aria-label="Exemplo de selo personalizado"><div className="sales-result-glow" /><div className="sales-result-photo"><img src="/Triso/Apresentacao/garoto_base.png" alt="Pessoa sorrindo em uma foto" /><img src="/Triso/Apresentacao/selo_triso.png" alt="Selo oficial da Triso Studio aplicado à foto" /></div><span className="sales-floating-card sales-floating-left">Sua marca<br /><b>em destaque</b></span><span className="sales-floating-card sales-floating-right"><Icon name="phone" /> Experiência<br />completa no celular</span></div></section>
    <section className="sales-demo" id="demonstracao" aria-labelledby="demo-title"><div className="sales-demo-copy"><span className="sales-kicker">PRÉVIA DO SITE</span><h2 id="demo-title">Veja como seu público vai usar.</h2><p>Experimente o site de selos da Triso Studio diretamente nesta página.</p><a className="sales-inline-link" href="/modelo-selo" target="_blank" rel="noreferrer">Abrir demonstração completa <Icon name="external" /></a></div><div className="sales-browser"><div className="sales-browser-bar"><span className="sales-browser-dots"><i /><i /><i /></span><span className="sales-browser-url">triso.studio.br/seu-selo</span><a href="/modelo-selo" target="_blank" rel="noreferrer" aria-label="Abrir demonstração em tela cheia"><Icon name="external" /></a></div><div className="sales-browser-viewport"><iframe src="/modelo-selo" title="Editor demonstrativo de selos Triso" loading="lazy" scrolling="auto" /></div></div></section>
    <section className="sales-before-after" id="exemplos" aria-labelledby="comparison-title"><div className="sales-before-copy"><span className="sales-kicker">EXEMPLO DE RESULTADO</span><h2 id="comparison-title">Da foto original ao selo personalizado.</h2><p>Uma imagem comum se transforma em uma peça da sua campanha em poucos segundos.</p></div><div className="sales-comparison"><article><div className="sales-photo"><img src="/Triso/Apresentacao/garoto_base.png" alt="Foto original do modelo" /></div><b>Foto original</b></article><span className="sales-comparison-arrow" aria-hidden="true"><Icon name="arrow" /></span><article><div className="sales-photo"><img src="/Triso/Apresentacao/garoto_base.png" alt="Foto do modelo com selo aplicado" /><img className="sales-photo-seal" src="/Triso/Apresentacao/selo_triso.png" alt="" /></div><b>Foto com selo</b></article></div></section>
    <section className="sales-steps-section" id="como-funciona" aria-labelledby="steps-title"><div className="sales-section-head"><span className="sales-kicker">COMO FUNCIONA</span><h2 id="steps-title">Uma experiência simples para quem participa.</h2></div><div className="sales-steps">{steps.map(step => <article className="sales-step" key={step.number}><span className="sales-step-number">{step.number}</span><i><Icon name={step.icon} /></i><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section>
    <section className="sales-manual" id="manual" aria-labelledby="manual-title"><div className="sales-section-head"><span className="sales-kicker">MANUAL DA EMPRESA</span><h2 id="manual-title">Seu guia para lançar uma campanha de selos.</h2></div><div className="sales-manual-list">{manualItems.map(([title, text], index) => <article className={`sales-manual-item ${openManual === index ? "open" : ""}`} key={title}><button type="button" onClick={() => setOpenManual(openManual === index ? -1 : index)} aria-expanded={openManual === index}><span>{String(index + 1).padStart(2, "0")}</span><strong>{title}</strong><b aria-hidden="true">+</b></button>{openManual === index && <div className="sales-manual-content"><p>{text}</p>{index === 3 && <div className="sales-copy-box"><q>{shareMessage}</q><button type="button" onClick={copyMessage} aria-live="polite">{copied ? "Mensagem copiada" : "Copiar mensagem"}</button></div>}</div>}</article>)}</div></section>
    <section className="sales-benefits" id="beneficios" aria-labelledby="benefits-title"><div className="sales-section-head"><span className="sales-kicker">BENEFÍCIOS</span><h2 id="benefits-title">Tudo para colocar sua comunidade em movimento.</h2></div><div className="sales-benefit-cards">{benefits.map(([title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="sales-cta"><span className="sales-kicker">PRÓXIMO PASSO</span><h2>Pronto para colocar sua comunidade em destaque?</h2><p>Criamos o selo e a página personalizada para sua marca. Você divulga o link e seu público participa.</p><div className="sales-actions sales-actions-center"><a className="sales-button sales-primary" href="mailto:oi@triso.com.br?subject=Solicitar%20meu%20site">Solicitar meu site <Icon name="arrow" /></a><a className="sales-button sales-secondary" href="/modelo-selo">Experimentar demonstração <Icon name="external" /></a></div></section>
    <footer className="sales-footer"><TrisoLogo light /><span>© 2026 Triso Studio</span><a href="mailto:oi@triso.com.br">oi@triso.com.br</a></footer>
  </main>;
}

export function PartyPresentationPage() {
  return <main className="sales-page sales-party-page"><a className="sales-back-link" href="/apresentacao">Voltar</a>
    <section className="sales-demo sales-party-demo" id="viewport-festa"><div className="sales-demo-copy"><span className="sales-kicker">VIEWPORT DA EXPERIÊNCIA</span><h2>Veja a página da festa funcionando.</h2><p>O convidado acessa pelo celular, escolhe a quantidade de fotos e cria a lembrança.</p><a className="sales-inline-link" href="/15-anos-isabella" target="_blank" rel="noreferrer">Abrir experiência completa <Icon name="external" /></a></div><div className="sales-browser"><div className="sales-browser-bar"><span className="sales-browser-dots"><i /><i /><i /></span><span className="sales-browser-url">triso.studio.br/15-anos-isabella</span><a href="/15-anos-isabella" target="_blank" rel="noreferrer" aria-label="Abrir festa em tela cheia"><Icon name="external" /></a></div><div className="sales-browser-viewport"><iframe src="/15-anos-isabella" title="Experiência digital da festa Isabella" loading="lazy" scrolling="auto" /></div></div></section>
    <section className="sales-before-after sales-party-gallery" id="resultados-festa" aria-labelledby="party-gallery-title"><div className="sales-before-copy"><span className="sales-kicker">RESULTADO DA EXPERIÊNCIA</span><h2 id="party-gallery-title">Da festa para uma lembrança pronta para compartilhar.</h2><p>Os momentos do evento viram uma composição personalizada para cada convidado.</p></div><div className="sales-party-result-flow"><div className="sales-party-source-stack"><article><div className="sales-photo"><img src="/Triso/Apresentacao/grupo1.webp" alt="Grupo de convidados na festa" /></div><b>Momento 01</b></article><article><div className="sales-photo"><img src="/Triso/Apresentacao/grupo2.webp" alt="Grupo de convidados na festa" /></div><b>Momento 02</b></article></div><span className="sales-comparison-arrow" aria-hidden="true"><Icon name="arrow" /></span><article className="sales-party-final"><div className="sales-photo"><img src="/Triso/Apresentacao/Lembranca_exemplo.png" alt="Lembrança final da festa da Isabella" /></div><b>Lembrança final</b></article></div></section>
    <section className="sales-party-occasions"><div className="sales-section-head"><span className="sales-kicker">CADA EVENTO TEM UM CLIMA</span><h2>Uma experiência com a cara da sua comemoração.</h2><p>Personalizamos molduras, cores, nomes e layouts para transformar o evento em uma lembrança compartilhável.</p></div><div className="sales-party-occasion-grid"><article><span>01</span><h3>15 anos & aniversários</h3><p>Uma lembrança especial para cada convidado.</p></article><article><span>02</span><h3>Casamentos & celebrações</h3><p>Momentos marcantes prontos para compartilhar.</p></article><article><span>03</span><h3>Formaturas & eventos</h3><p>Uma experiência digital com identidade própria.</p></article></div></section>
    <header className="sales-header"><div className="sales-header-inner"><TrisoLogo light /><nav className="sales-nav" aria-label="Navegação principal"><a href="#experiencia-festa">Experiência</a><a href="#como-funciona-festa">Como funciona</a><a href="#entrega-festa">Entrega</a></nav><a className="sales-header-cta" href={whatsappHref} target="_blank" rel="noreferrer">Criar experiência <Icon name="arrow" /></a></div></header>
    <section className="sales-hero" id="experiencia-festa"><div className="sales-hero-copy"><span className="sales-kicker">EXPERIÊNCIAS DIGITAIS PARA FESTAS</span><h1>Transforme cada foto em uma <em>lembrança da sua festa.</em></h1><p>Uma página personalizada para seus convidados enviarem fotos, escolherem uma moldura e baixarem uma arte pronta para compartilhar.</p><div className="sales-actions"><a className="sales-button sales-primary" href={whatsappHref} target="_blank" rel="noreferrer">Falar sobre minha festa <Icon name="arrow" /></a><a className="sales-button sales-secondary" href="/15-anos-isabella">Ver experiência Isabella <Icon name="external" /></a></div></div><div className="sales-hero-result"><div className="sales-result-glow" /><div className="sales-result-photo sales-party-frame"><img src={fitaIsabella4} alt="Moldura de festa da Isabella com quatro fotos" /></div></div></section>
    <section className="sales-steps-section" id="como-funciona-festa"><div className="sales-section-head"><span className="sales-kicker">COMO FUNCIONA</span><h2>Uma experiência simples para todos os convidados.</h2></div><div className="sales-steps"><article className="sales-step"><span className="sales-step-number">01</span><i><Icon name="image" /></i><h3>O convidado acessa o link</h3><p>O endereço pode ser enviado no convite, mesa, QR Code ou grupo da festa.</p></article><article className="sales-step"><span className="sales-step-number">02</span><i><Icon name="crop" /></i><h3>Escolhe uma foto e uma moldura</h3><p>A pessoa envia a foto pelo celular e escolhe a quantidade de fotos da composição.</p></article><article className="sales-step"><span className="sales-step-number">03</span><i><Icon name="download" /></i><h3>Baixa e compartilha</h3><p>A lembrança fica pronta para Stories, Reels, status e álbum da festa.</p></article></div></section>
    <section className="sales-benefits" id="entrega-festa"><div className="sales-section-head"><span className="sales-kicker">ENTREGA DA EXPERIÊNCIA</span><h2>Uma solução bonita antes, durante e depois da festa.</h2></div><div className="sales-benefit-cards"><article><span>01</span><h3>Identidade da festa</h3><p>Molduras criadas com nome, idade, cores e elementos da celebração.</p></article><article><span>02</span><h3>Link exclusivo</h3><p>Uma página própria para concentrar a experiência e orientar os convidados.</p></article><article><span>03</span><h3>Memórias compartilháveis</h3><p>Cada convidado sai com uma lembrança pronta para publicar.</p></article></div></section>
    <section className="sales-cta"><span className="sales-kicker">PRÓXIMO PASSO</span><h2>Vamos criar a experiência da sua festa?</h2><p>Conte a data, o estilo e a quantidade de convidados. A Triso monta o caminho ideal.</p><div className="sales-actions sales-actions-center"><a className="sales-button sales-primary" href={whatsappHref} target="_blank" rel="noreferrer">Chamar no WhatsApp <Icon name="arrow" /></a><a className="sales-button sales-secondary" href="/15-anos-isabella">Ver exemplo completo <Icon name="external" /></a></div></section>
    <footer className="sales-footer"><TrisoLogo light /><span>© 2026 Triso Studio</span><a href={whatsappHref} target="_blank" rel="noreferrer">WhatsApp</a></footer>
  </main>;
}
